# Generated by Django 2.2.7 on 2019-11-20 02:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='acciones_stkholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acciones_positivas', models.CharField(max_length=200)),
                ('acciones_negativas', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Costeos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='costos_directos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='costos_fijos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='costos_indirectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='costos_variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='indicadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_indicador', models.CharField(max_length=30)),
                ('linea_base', models.DecimalField(decimal_places=2, max_digits=9)),
                ('meta_indicador', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='municipios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('municipios', models.ManyToManyField(to='personas.municipios')),
            ],
        ),
        migrations.RemoveField(
            model_name='persona',
            name='hermanos',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='madre',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='padre',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='pareja',
        ),
        migrations.AddField(
            model_name='persona',
            name='nivel_estudios',
            field=models.CharField(choices=[('B', 'BACHILLERATO'), ('L', 'LICENCIATURA'), ('M', 'MAESTRIA'), ('D', 'DOCTORADO'), ('PD', 'POSTDOCTORADO')], default='ES', max_length=2),
        ),
        migrations.AddField(
            model_name='persona',
            name='ocupacion',
            field=models.CharField(choices=[('ES', 'ESTUDIANTE'), ('EM', 'EMPLEADO'), ('IN', 'INVESTIGADOR'), ('O', 'OTRO')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='genero',
            field=models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], default='B', max_length=1),
        ),
        migrations.CreateModel(
            name='Zona_geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiones', models.ManyToManyField(to='personas.region')),
            ],
        ),
        migrations.CreateModel(
            name='stk_holder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente_involucrado', models.CharField(max_length=200)),
                ('nivel_interes', models.CharField(choices=[('B', 'BAJO'), ('M', 'MEDIO'), ('A', 'ALTO')], max_length=1)),
                ('nivel_influencia', models.CharField(choices=[('B', 'BAJO'), ('M', 'MEDIO'), ('A', 'ALTO')], max_length=1)),
                ('acciones_stkholder', models.ManyToManyField(to='personas.acciones_stkholder')),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=200)),
                ('objetivo', models.CharField(max_length=200)),
                ('duracion_inicio', models.DateTimeField(verbose_name='Fecha_de_Inicio')),
                ('duracion_fin', models.DateTimeField(verbose_name='Fecha_de_Finalizacion')),
                ('costeos', models.ManyToManyField(to='personas.Costeos')),
                ('indicadores', models.ManyToManyField(to='personas.indicadores')),
                ('stk_holder', models.ManyToManyField(to='personas.stk_holder')),
                ('zona_geo', models.ManyToManyField(to='personas.Zona_geo')),
            ],
        ),
        migrations.AddField(
            model_name='indicadores',
            name='proyecto',
            field=models.ForeignKey(on_delete=None, related_name='P_indicadores', to='personas.Proyectos'),
        ),
        migrations.AddField(
            model_name='costeos',
            name='costos_directos',
            field=models.ManyToManyField(related_name='costos_d', to='personas.costos_directos'),
        ),
        migrations.AddField(
            model_name='costeos',
            name='costos_fijos',
            field=models.ManyToManyField(related_name='costos_f', to='personas.costos_fijos'),
        ),
        migrations.AddField(
            model_name='costeos',
            name='costos_indirectos',
            field=models.ManyToManyField(related_name='costos_i', to='personas.costos_indirectos'),
        ),
        migrations.AddField(
            model_name='costeos',
            name='costos_variables',
            field=models.ManyToManyField(related_name='costos_v', to='personas.costos_variables'),
        ),
    ]
